### ISSUE TITLE
TODO: TUI

### ISSUE THREAD

**Issue by henryiii** [henryiii/uproot-browser#12]
- [x] Rename `tui` to `browse`
- [x] Use a useful title instead of "Plotext integration in rich - test"
- [x] Output errors into the display.
- [x] Maybe have a nice logo or something in the display before anything is plotted. Maybe "uproot⁴-browser\npowered by Hist" or something. :)
- [x] Can we change that little bug icon in the top left?
- [x] Maybe add a red close "x" in the top menu? (optional)
- [x] Provide visual feedback when hovering, etc. over the tree (mimic code_viewer)
- [x] Keyboard support (I think that's already there, just needs the above for visual assistance in navigating)
-  Some common errors should have nice messages instead of a traceback, like "Unplottable object X selected" or something. Could include various bits of information for some unplottable objects. (we can save this for later)

After this (1 week or so?) we can make a 0.3 release and we should be able to propose the move into Scikit-HEP.

Also: think about ways to keep the display alive while waiting for the histogram. I think this could be done by the plot starting the histogram via await, and then emitting a event when it is done.

And then we can think about ways to control the plot. A simple one could be recomputing the histogram on mouse wheel up/down with more/less bins. :)

**Comment by henryiii** [comment]
Some ideas: https://patorjk.com/software/taag/#p=testall&f=Babyface%20Lame&t=uproot-browser%20

```
                          __      __                                
 __ _____  _______  ___  / /_4___/ /  _______ _    _____ ___ ____   
/ // / _ \/ __/ _ \/ _ \/ __/___/ _ \/ __/ _ \ |/|/ (_-</ -_) __/   
\_,_/ .__/_/  \___/\___/\__/   /_.__/_/  \___/__,__/___/\__/_/      
   /_/                                                              
           powered by Hist
```

```
┬ ┬┌─┐┬─┐┌─┐┌─┐┌┬┐4 ┌┐ ┬─┐┌─┐┬ ┬┌─┐┌─┐┬─┐  
│ │├─┘├┬┘│ ││ │ │───├┴┐├┬┘│ ││││└─┐├┤ ├┬┘  
└─┘┴  ┴└─└─┘└─┘ ┴   └─┘┴└─└─┘└┴┘└─┘└─┘┴└─  
                          powered by Hist
```

**Comment by henryiii** [comment]
We should probably rename the "tui" command to something more friendly, like "browse".
